# Generated by Django 3.0.7 on 2020-07-22 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0035_auto_20200721_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_products', to='foodcartapp.Order', verbose_name='Заказ'),
        ),
    ]
