# Generated by Django 3.0.7 on 2020-07-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0036_auto_20200722_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=8, verbose_name='цена'),
            preserve_default=False,
        ),
    ]
