# Generated by Django 3.0.7 on 2020-07-25 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20200725_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('online', 'Электронно'), ('cash', 'Наличностью')], default='cashс', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime.now(), verbose_name='Дата создания заказа'),
        ),
    ]
