# Generated by Django 3.0.7 on 2020-07-26 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20200725_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurants',
            field=models.ManyToManyField(related_name='orders', to='foodcartapp.Restaurant', verbose_name='Рестораны, которые приготовят заказ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 12, 23, 27, 425286), verbose_name='Дата создания заказа'),
        ),
    ]
