# Generated by Django 3.0.7 on 2020-07-26 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20200726_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='restaurants',
        ),
        migrations.AlterField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 12, 26, 5, 83408), verbose_name='Дата создания заказа'),
        ),
    ]
